---
apiVersion: v1
kind: Namespace
metadata:
  name: restaurant-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-web-app-deployment
  namespace: restaurant-ns
spec:
  replicas: 4
  selector:
    matchLabels:
      app: restaurant-web-application
  template:
    metadata:
      labels:
        app: restaurant-web-application
    spec:
      containers:
      - name: restaurant-web-app-container
        image: titi10/node.js-restaurant-web-application:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      # Commented is for private repository
      #imagePullSecrets:
      #- name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-web-application
  namespace: restaurant-ns
spec:
  selector:
    app: restaurant-web-application
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer