name: Creating Node.js app image and deploying dockerhub
on:
  push:
     branches:
     - main
     - release/*
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Image Tagging uses GitHub Build number in K8s manifest yaml file
      run: |
        echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV
      
    - name: Build, Tag, and Push Node.js image to Docker Hub
      env:
        DOCKER_HUB_REPOSITORY: ${{ secrets.DOCKER_HUB_USERNAME }}/node.js-restaurant-web-application
        IMAGE_TAG: ${{ github.run_number }}
      run: |
        docker build -t $DOCKER_HUB_REPOSITORY:$IMAGE_TAG .
        docker push $DOCKER_HUB_REPOSITORY:$IMAGE_TAG
